### ISSUE TITLE
[Suggestion] API

### ISSUE THREAD

**Issue by mega12345mega** [ScreamingSandals/NMSMapper#4]
Can you setup an API on the website?

About a week ago, I setup a screen scraper to download the complete mappings for any version, which I'm currently using to generate a NMS library for Spigot. This library wouldn't require any reflection (on the user's end), as it creates an interface, which can hide the reflection and handle different Minecraft versions in the background.

Unless you're planning on keeping the mapping viewer website the exact same, it would be convenient to be able to request the mapping data directly.

While being able to download a complete .json file would be ideal, just having the ability to request information for a specific class would be super helpful.

Thanks!

**Comment by Misat11** [comment]
Well the webpage is only a static content hosted on github pages, so I don't think I am able to make an api for it. However NMSMapper is not only website, but also a tool which can generate reflection accessors to handle multiple versions and it has all the data in .json files inside its jar, which can be found here: https://repo.screamingsandals.org/#/releases/org/screamingsandals/nms/nms-mapper-standalone, so you may want to use these json files instead of scrapping the website :)

**Comment by mega12345mega** [comment]
That works for me, thanks!
